server {
  listen 8080;
  listen [::]:8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location ~* \.mjs$ {
    default_type application/javascript;
    try_files $uri =404;
  }

  location ~* \.wasm$ {
    default_type application/wasm;
    try_files $uri =404;
  }

  location / {
    try_files $uri /index.html;
  }
}
